name: default

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build
    - name: Run meilisearch
      run: chmod +x run-meili.sh && ./run-meili.sh
    - name: Test
      run: cd src/Tests && dotnet test --no-restore --verbosity normal
